<a href="https://colab.research.google.com/github/MrAgabaidu/Data-Sciences/blob/main/Neural%20Networks%20and%20Deep%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **DEEP LEARNING/NUERAL NETWORK**

In this notebook i use the famous tensor flow library for nueral network precisely image classification

## **Tensorflow Basics**

## *In this part of the notebook i will be working with the basics of tensor flow using the new eager execution*

In [1]:
import tensorflow as tf

In [3]:
hello=tf.constant('Hello world')

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [9]:
f=tf.constant(100)

In [7]:
type(f)

tensorflow.python.framework.ops.EagerTensor

In [11]:
#sess = tf.Session()

In [12]:
hello.numpy()

b'Hello world'

In [15]:
type(f.numpy())

numpy.int32

In [16]:
# Operations

In [21]:
x=tf.constant(2)
y=tf.constant(3)

In [32]:
print('addition:',(x+y).numpy())
print('subtraction:',(x-y).numpy())
print('multiplication:',(x*y).numpy())
print('division:',(x/y).numpy())


addition: 8
subtraction: -1
multiplication: 6
division: 0.6666666666666666


In [23]:
 #Placeholder

In [35]:
x=20
y=30
add=tf.add(x, y)
sub=tf.subtract(x,y)
mul=tf.multiply(x,y)

In [36]:
print('Addition:', add.numpy())

Addition: 50


In [37]:
import numpy as np

In [53]:
a = np.array([[5.0, 5.0, 5.0], [2, 2, 2],[1,1,1]])
b = np.array([[2.0, 5, 1],[2.0, 5,1], [2,5,1]])

In [54]:
b

array([[2., 5., 1.],
       [2., 5., 1.],
       [2., 5., 1.]])

In [55]:
mat1=tf.constant(a)
mat2=tf.constant(b)

In [56]:
mul=tf.matmul(mat1, mat2)
m=print('Multiplication:', mul.numpy())

Multiplication: [[30. 75. 15.]
 [12. 30.  6.]
 [ 6. 15.  3.]]


## **MNIST Dataset**

## *The famous MNIST dataset is a dataset of hand written digits and this part of the notebook i will perform image recognition on this dataset to recognize the number using the darkness of the image*